components/common/Chip.tsx
모임찾기와 리뷰 페이지에서 사용되는 필터링 버튼을 작성하였습니다
사용예시
```jsx
const [selectedFilter, setSelectedFilter] = useState<string>("전체");
const handleFilterChange = (filter: string) => {
// 조회 api 추가
setSelectedFilter(filter);
};
```
조회 api 부분 이쪽에 추가하여 사용하시면 될 것 같습니다.
```jsx
<div className="flex gap-4 p-4">
<Chip
label="전체"
selected={selectedFilter === "전체"}
onClick={() => handleFilterChange("전체")}
/>
<Chip
label="오피스 스트레칭"
selected={selectedFilter === "인도 스트레칭"}
onClick={() => handleFilterChange("야무진 스트레칭")}
/>
<Chip
label="마인드폴니스"
selected={selectedFilter === "한국 스트레칭"}
onClick={() => handleFilterChange("안 야무진 스트레칭")}
/>
</div>
```
선택한 필터는 검은색 색상이 들어가있습니다.
모바일 환경  사이즈가 작아지는 반응형 기능이 구현 되어있습니다.
=> ✨ CHIP 공통 컴포넌트 추가

components/common/DateFilter.tsx
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
날짜와 지역 필터에 사용되는 공용컴퍼넌트를 제작하였습니다.
기본값
필터링시
사용예시
```jsx
const regions = ["지역전체", "서울", "부산", "대구", "광주"];
const [selectedRegion, setSelectedRegion] = useState("지역전체");
<DateFilter
isDefault={selectedRegion === "지역전체"}
label={selectedRegion}
onClick={() => setIsDropdownOpen(!isDropdownOpen)}
/>
```
선택된 부분의 초기값을 설정해주어 사용해주시면 됩니다.
모바일 반응형
기본값 120px 40px
모바일 화면에 경우 110px 36px 인 반응형으로 구현하였습니다.
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
=> ✨ DateFilter 공용컴포넌트 제작

components/Button.tsx, package-lock.json, package.json
=> 🌱  react-cookie 라이브러리 설치

components/common/DateFilter.tsx, components/common/SortFilter.tsx
정렬필터를 작성하였습니다
모바일 초과 화면
모바일화면
사용예시
```jsx
const regions = ["지역전체", "서울", "부산", "대구", "광주"];
const [selectedRegion, setSelectedRegion] = useState("지역전체");
<DateFilter
label={selectedRegion}
onClick={() => setIsDropdownOpen(!isDropdownOpen)}
/>
```
https://github.com/user-attachments/assets/1f6b8308-edd0-4c27-8c10-5ffbfcebd5d7
드롭다운과 함계 사용이 가능합니다
필터 부분을 ui와 선택시 transition 되는 부분이 없어 컴포넌트를 따로 제작해보았습니다
=> ✨ 정렬 필터 공용컴포넌트 작성

lib/axios.ts
> ex) #이슈번호, #이슈번호
- 사용 예시
```
import { axiosInstance } from "@lib/axios";
const response = await axiosInstance.post("/auths/signin", data);
```
=> ✨ axios instance 생성

app/layout.tsx, lib/axios.ts, package-lock.json, package.json, providers/ReactQueryProvider.tsx, tsconfig.json
=> ✨ react-query provider 설정

tsconfig.json, utils/cookieUtils.ts
매번 `const cookies = new Cookies();` 로 인스턴스 생성하지 않도록 만들었습니다ㅎㅎ
- 사용 예시
```
import { setCookie, getCookie, removeCookie } from "@utils/cookieUtils";
setCookie("token", token, { path: "/" });
getCookie("token");
removeCookie("token");
```
=> ✨ 쿠키 유틸리티 파일 생성

components/common/Button.tsx
large 사이즈일 때 max width가 고정되어 있어서 더 늘어나지 않는 오류 수정했습니다.
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
=> ✨ button 컴포넌트 width 오류 수정

app/list/layout.tsx, app/list/page.tsx, components/common/DateFilter.tsx, components/common/SortFilter.tsx
모임찾기 정렬 부분을 퍼블리싱 완료하였습니다.
이후 레이아웃을 max-w > padding 으로 수정완료했습니다
=> 🎨 모임찾기 정렬 퍼블리싱

features/auth/components/AuthPageLayout.tsx
=> ✨ 회원가입/로그인 링크 연결

components/common/Chip.tsx, components/common/DateFilter.tsx, components/common/SortFilter.tsx
회의 결과 공용컴포넌트의 active를 제거하겠습니다!
=> 🎨 칩 정렬 공용컴포넌트 active 제거

components/common/ChipInfo.tsx
chip-info 컴포넌트 작업했습니다.
-사용법-
`<ChipInfo info="1월 7일" variant="mint" />`
더 추가되어야 하는 기능 있으면 말씀해주세요!
=> ✨ chip-info 컴포넌트 구현

components/common/Button.tsx
button 컴포넌트에 onClick props 추가했습니다.
자꾸 번거롭게 해드려서 죄송합니다 ㅜㅜ
또 빠져있는 기능 있으면 바로 말씀해주세요!
=> ✨ button 컴포넌트 onClick props 추가

app/list/page.tsx, components/common/Chip.tsx, components/common/DateFilter.tsx, components/common/SortFilter.tsx
스크럼 회의 내용이였던 레이아웃 일치작업
1. 반응형 sm > md 일치작업
2. 페이지 페딩 px-4 md:px-6 lg:px-24 적용하였습니다.
=> 🎨 반응형 sm->md 수정, 페이지 패딩 수정

app/(layout_auth)/signin/page.tsx, app/(layout_auth)/signup/page.tsx, features/auth/components/AuthPageContainer.tsx
네이밍이 제일 어렵네요... AuthPageContainer ? AuthPageWrapper?  
컴포넌트 이름을 어떻게 지어야 할지 항상 고민이에요ㅠ
=> 🚚  AuthLayout과 혼동되지 않도록 파일 이름 변경

app/(layout_dafault)/layout.tsx, app/(layout_dafault)/review/page.tsx
각자 페이지 최상단 div태그에 pt-6 md:pt-8 적용해주시면 될것 같습니다! (상단에 패딩 필요 없는 페이지 제외)
참고 : [🎨 style: review 페이지 pt 적용](https://github.com/Ever-Ring/EverRing/commit/d1e71ae8e892b14f9cd0e550ad28d19a7b176b70)
=> 🐛 default layout py값 제거

components/common/Chip.tsx
=> 🎨 chip font-medium 추가

components/common/Button.tsx
=> 🐛 button small size 수정

app/(layout_dafault)/list/page.tsx, app/globals.css, app/list/layout.tsx, components/common/DateFilter.tsx, components/common/SortFilter.tsx, features/review/components/FilterBar.tsx, package.json
날짜 정렬 필터 캘린더 모달 추가
기능
1. 모달 외부 클릭시 모달창 닫기
2. 날짜 선택후 적용 버튼 누른 경우 날짝 선택 확정
3. 날짜 초기화 기능 구현
4. 모바일 화면 시 반응형 위치 조정
5. 모달 외부 클릭시 자동 닫기
사용 예시
사용 구조 변경
```jsx
<DateFilter onDateSelect={handleDateChange} />
```
```jsx
// 날짜가 변경될 때 API 요청을 보낼 수 있도록 상태 업데이트
const handleDateChange = (date: string | undefined) => {
console.log("API 요청: 필터링할 날짜 =", date || "전체");
};
```
날짜가 변경될 때 부모 컴포넌트에서 데이터 활용 가능합니다.
1. 캘린더 커스텀 시 확인을 위해 css에 설명 주석달아두었습니다
2. date-fns, react-datepicker 라이브 러리 설치 npm install 필요합니다.
=> ✨ 날짜 정렬필터 모달 추가

app/(layout_dafault)/list/page.tsx
page에 패딩을 걸었던 구조였습니다.
병합과정에서 생긴 중복 패딩 제거했습니다.
=> 🎨  병합과정에서 생긴 중복 패딩 제거

components/common/DateFilter.tsx
날짜 필터 옆 화살표 버튼 누락된 부분 추가 하였습니다
=> 🎨  필터 화살표 추가

features/mypage/components/EditProfileModal.tsx, features/mypage/components/MyProfile.tsx
>
> 마이페이지 프로필 컴포넌트 데이터 로딩 시 스켈레톤 추가 (필요할 지 모르겠으나 일단 넣어놨습니다.)
> 프로필 수정 모달의 불필요한 콘솔로그 삭제, 에러 핸들링 추가, 모달 닫기 버튼 크기 수정 작업했습니다.
> 프로필 수정 모달에서 에러 핸들링을 어떻게 하면 좋을 지...모르겠네요 좋은 의견있으면 알려주세요..!
=> ✨ 마이페이지 프로필 컴포넌트와 모달 수정

apis/AuthApi.ts, apis/ReviewApi.ts, tsconfig.json, types/reviewApi.d.ts
=>  ✨ review api 생성

utils/dateFormatter.ts
> 
> 기존 날짜 포맷 유틸 함수 수정하고(YYYYMMDD 형식) 새로운 함수 추가했습니다.(M월 D일 tt:mm)
>
=> ✨ 날짜 포맷 유틸 함수 수정

app/(layout_dafault)/list/page.tsx, components/common/LocationFilter.tsx, features/review/components/FilterBar.tsx
> ex) #이슈번호, #이슈번호
지역 필터 제작 완료했습니다.
드롭다운 형태도 구현 완료했습니다
사용예시
```jsw
// 정렬 옵션 변경 콜백 (SortFilter에서 호출)
const handleLocationChange = (sortValue: string) => {
state 선언 필요
setSelectedLocation(sortValue);
console.log("API 요청: 정렬 기준 =", sortValue);
};
리스트 페이지 경우
<LocationFilter  onLocationChange={handleLocationChange} />
```
=> ✨  로케이션 공용 필터추가 + 드롭다운

app/(layout_dafault)/review/page.tsx, constants/auth.ts, features/auth/components/AuthPageContainer.tsx, features/review/components/ReviewContentContainer.tsx, features/review/hooks/useGetReviewData.ts, lib/axios.ts, package-lock.json
=> ✨ 리뷰페이지 data fetching

app/(layout_dafault)/review/page.tsx, features/review/components/RatingContainer.tsx, features/review/components/ReviewContentContainer.tsx, features/review/hooks/useGetReviewScore.ts, types/review.d.ts
initial score를 내려주도록 바꿨는데 이렇게 사용하게 되면 초기화면에서는 RatingBreakdown 애니메이션이 동작할 수가 없네요.... 
이 문제는 이슈에 등록해놓고 나중에 수정해보겠습니다ㅎㅎ 할 일이 너무 많네요ㅠ
=> ✨ 리뷰페이지 별점 data fetching

apis/AuthApi.ts, apis/GatheringApi.tsx, app/(layout_dafault)/mypage/page.tsx, features/mypage/components/MypageCard.tsx, features/mypage/components/MypageCardList.tsx, features/mypage/components/MypageContent.tsx, features/mypage/hooks/useGetGatheringsJoined.ts
> #80 
> 마이페이지 컨텐츠 영역 데이터 페칭 및 ui 작업했습니다.
> 버튼 인터랙션이 필요한 부분들은 아직 작업 안 됐습니다. 데이터 조회만 가능합니다. 추가로 나의 리뷰 / 작성한 리뷰 영역은 아직 데이터가 없어서 일단 임시로 작성해놨습니다.
PC View
Mobile View
> 지금 네이밍도 어지럽고 구조도 복잡한 것 같은데...추후 머리를 좀 식히고 다시 생각해봐야 할 것 같습니다...🫠
=> ✨ 마이페이지 컨텐츠 영역 추가 및 데이터 페칭

features/mypage/components/MypageCard.tsx, features/mypage/components/MypageContent.tsx, features/review/components/ReviewContentContainer.tsx
=> 🐛 모달 여러번 열리는 버그 해결

app/(layout_dafault)/review/page.tsx, components/common/TabItem.tsx, components/common/TabMenu.tsx, constants/tab.ts, features/review/components/RatingBreakdown.tsx, features/review/components/RatingContainer.tsx, features/review/constants/query.ts, features/review/hooks/useGetReviewData.ts, types/reviewApi.d.ts
그동안 나무링 구름링 위치를 바꿔서 사용하고 있었어요.... 😹
어쩐지 필터링이 이상하더라
=> 🐛 리뷰페이지 필터링 및 자잘한 버그 수정

.github/workflows/build_and_test.yml, features/mypage/components/StateChip.test.tsx
>
> codecov 리포트를 추가하도록 깃헙액션 워크플로우 수정했습니다.
>
=> 🌱 codecov 추가

.github/workflows/build_and_test.yml
>
> codecov에서 자동으로 pr에 코멘트를 달아주는데, 이 때문에 기존 액션이 이미 코멘트가 있다고 인식해서 lighthouse 결과를 코멘트에 추가하지 못하는 것 같습니다.
> 일단 수정해봤는데...될 지 모르겠어요...😭
>
=> 🌱 GitHub Actions 워크플로우 수정

README.md
=> 📝 리드미 파일 수정

components/common/SortFilter.tsx, features/review/components/ReviewContentContainer.tsx, features/review/constants/query.ts, features/review/constants/review.ts
=> ♻️ refactor: 정렬 옵션 최신순 -> 오래된순으로 변경

apis/GatheringListApi.tsx, app/(layout_dafault)/list/page.tsx, components/common/GatheringList.tsx, features/list/hooks/useGetGatherings.ts
무한스크롤 적용하였스습니다.
1. 무한스크롤 적용완료
2. 초기데이터 ssr 보낸 이후 csr로 무한스크롤 구현(예정)
=> ✨ 모임페이지 무한 스크롤 적용

hooks/useLogout.ts, middleware.ts
> #80 
> 로그인 상태에 따라 mypage 접근을 제어하는 미들웨어 추가했습니다.
> 지금은 로그인 안된 상태에서 마이페이지 접근시 로그인 페이지로 가게 해놨는데 괜찮나요?
=> ✨ 로그인 상태에 따른 mypage 접근 제어 미들웨어 추가

features/review/components/ReviewContentContainer.tsx
=> 🎨 ReviewContentContainer의 마크업 일부 수정

features/mypage/components/EditProfileModal.tsx, features/mypage/components/MyProfile.tsx
> #80
> 마이페이지의 기존 로직을 수정했습니다.
> 내 프로필 정보는 기존에 쿼리를 통해 가져오던 방식에서 로컬 스토리지에 저장된 값을 사용하는 방식으로 변경했습니다.
> 프로필 수정 모달에서는 수정 요청이 성공하면 전역 상태의 값도 함께 업데이트되도록 수정했습니다.
>
=> ✨ 마이페이지 기존 로직 수정

.github/workflows/build_and_test.yml, codecov.yml, jest.config.ts, jest.setup.ts, package-lock.json, package.json
> 
> jest 셋팅 및 codecov 워크플로우 수정했습니다.
>
=> 🧪 jest 셋팅 및 codecov 워크플로우 수정

components/common/Gnb.tsx
> #61 
> 찜한 모임 수만큼 숫자 뱃지가 표시되는 작업했습니다.
PC View
Mobile View
>
=> ✨ Gnb 찜한 모임 숫자 뱃지 추가

__mocks__/svg.ts, components/common/TabItem.test.tsx, components/common/TabItem.tsx, components/common/TabMenu.test.tsx, components/common/TabMenu.tsx, jest.config.ts, tsconfig.json
=> ✅ Tab 관련 컴포넌트 테스트 코드 작성

app/(layout_dafault)/liked/page.tsx, components/common/GatheringList.tsx, features/liked/FavoriteGatheringList.tsx, features/list/hooks/useGatheringFilters.ts, features/list/hooks/useGetIdGatherings.ts
필터 페이지 필터링 적용(모임리스트와 동일 필터)
찜하기 모두비우기 버튼 제작 완료했습니다.
차후 필터 부분 선언적 코드 만들기 위해 컴포넌트로 분리할 예정입니다.
=> ✨ 찜하기 페이지 필터, 비우기 버튼 적용

app/(layout_dafault)/list/page.tsx
=> ✨ 리스트 페이지 모임 만들기 버튼에 모달 연결

middleware.ts
기존에 있던 미들웨어 코드 수정하여 루트로 접근하면 리스트 페이지로 리다이렉트 되게끔 했습니다!
=> ✨ "/" -> "/list" redirect 추가

components/common/Gnb.tsx
> 
> Gnb 모바일 반응형 스타일 수정했습니다.
>
=> 🎨 Gnb 모바일 반응형 스타일 수정

constants/gathering.ts, features/mypage/components/MypageCard.tsx
> 
> 최소 모집인원 상수 추가하였습니다.
> 마이페이지에서 모임의 개설 여부 확인하는 로직 수정했습니다.
>
=> ✨ 최소 모집인원 상수 추가 및 마이페이지 수정

apis/GatheringApi.tsx, components/common/CreateModal.tsx, components/common/CreateModalInput.tsx, types/gathering.d.ts
모임 생성 시 이미지 안들어가는 오류 수정 및 이미지 전체적으로 string -> file  처리
=> 🐛 모임 생성 시 이미지 안들어가는 오류 수정

app/(layout_dafault)/list/page.tsx, features/list/hooks/useGatheringFilters.ts
> ex) #이슈번호, #이슈번호
모임리스트 필터 관련 수정 있습니다.
1. 구름링 시 지역필터 제거
2. 참여 인원순 시 내림차순 변경
=> ✨ 모임리스트 필터 수정

features/mypage/components/MypageCard.tsx, features/mypage/components/MypageCardList.tsx, types/gathering.d.ts
> 
> MypageCard 컴포넌트의 props를 단일 객체로 넘기도록 수정했습니다.
> 기존 MypageCardList의 중첩 삼항 연산자를 제거했습니다. 
>
=> ♻️ MypageCard props 수정

app/(layout_dafault)/list/page.tsx, features/list/CreateGatheringButton.tsx
1. 모임만들기 시 로그인한 사용자만 이용가능하게 처리하였습니다.
=> ✨ 모임만들기 로그인된 사용자 이용

app/(layout_dafault)/mypage/page.tsx, components/common/GatheringClosureNotice.tsx, features/mypage/components/EditProfileModal.tsx, features/mypage/components/MypageCard.tsx, features/mypage/components/MypageCardList.tsx, features/mypage/components/MypageContent.tsx, features/mypage/components/WriteReviewModal.tsx, types/gathering.d.ts
>
> 마이페이지 나의 모임에서 모집 취소된 모임의 경우 블랙처리하는 작업했습니다. (현재 마이페이지에서만 사용가능한 구조로 되어있는데 추후 공통 컴포넌트로 쓰일 수 있도록 수정하겠습니다.)
> 리뷰 작성 모달에 별점 애니메이션을 추가했습니다.
PC View
Mobile View
>
=> ✨ 마이페이지 취소된 모임 처리 및 리뷰 작성 모달 별점 애니메이션 추가

utils/dateFormatter.test.ts, utils/dateFormatter.ts
> 
> dateFormatter 테스트 코드에 formatDateTime 테스트 스위트 추가했습니다.
>
=> 🧪 dateFormatter 테스트 스위트 추가

app/(layout_dafault)/list-detail/[gatheringId]/page.tsx, features/list-detail/components/ListDetailContent.tsx, features/list-detail/components/Pagination.tsx, features/list-detail/components/ReviewSection.tsx, features/list-detail/hooks/useGetReviewList.ts, features/list-detail/hooks/usePagination.ts, types/review.d.ts
기존의 상세페이지 리뷰 부분 서버사이드로 렌더링 하는 작업 추가했습니다!
테스트 해보시다가 이상한 점 있으면 편하게 말씀해주세요!
=> ✨ 상세페이지 리뷰 부분 수정사항

app/(layout_dafault)/list/page.tsx, constants/filter.ts, features/list/hooks/useInfiniteGetGatherings.ts, features/list/utills/gatheringsQuery.ts
1. 모임리스트 페이지 SSR적용했습니다.
2. HydrationBoundary 를 활용하여 초기 필터(유형 달램핏) 기준으로 10개의 데이터 ssr로 가져오도록 구현하였습니다
=> ♻️ 모임리스트 페이지  SSR 적용

components/common/GatheringItem.tsx
1. 마우스 오버 시 클릭가능한 느낌 주는 포인터 추가
2. 마우스 올릴 경우 약간 어두워지는 애니메이션 추가
3. alt -> 마감된 챌린지를 삭제하려면 클릭하세요로 변경
=> ✨ 마감된 모임 아이템 호버 이벤트 추가

features/mypage/components/WriteReviewModal.tsx, middleware.ts
> 
> - 로그인한 사용자의 경우 signin, signup, 랜딩페이지 접근 못하게 미들웨어 수정했습니다.
> 혹시나 제가 놓친 부분이 있다면 바로 바로 알려주시면 감사하겠습니다 🙇‍♀️
=> ✨ auth 페이지 접근 제한 미들웨어 수정

components/common/Button.test.tsx
=> 🧪 Button 테스트 코드 작성

components/common/GatheringItem.tsx, tailwind.config.ts
모임찾기, 찜하기에 들어가는 모임아이템 참여인원 프로그래스바의 차오르는 애니메이션 추가하였습니다.
프리티어로 애니메이션 클래스가 링트에 맞지않게 자동수정되는 부분이 있어 잠시 링트 해제하였습니다. 시연이후 리팩토링하겠습니다.
=> ✨  게더링아이템 프로그래스 에니메이션추가

components/common/DropDown.test.tsx, components/common/DropDownItems.test.tsx
DropDown 컴포넌트와 DropDownItmes 컴포넌트 테스트 코드 작성했습니다.
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
=> 🧪 Dropdown 테스트 코드 작성

components/common/Button.test.tsx, components/common/ChipInfo.test.tsx
ChipInfo 컴포넌트 테스트 코드 작성했습니다.
Button 컴포넌트의 테스트 코드 테스트명을 should ~ when 형식으로 수정하였습니다.
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
=> 🧪 ChipInfo 테스트 코드 작성

features/list/components/FilterOptions.tsx, features/list/components/ListContainer.tsx, types/filters.ts
1. filteroptions flex between 디자인 수정
2. filteroptions 컴포넌트화 하면서 누락된 sortBy 추가
3. sortBy 프롭스로 전달 완료하였습니다.
=> ♻️  filteroptions 필터 보여지는 내용, 디자인 수정

components/common/Button.tsx, components/common/ReviewItemWithImage.tsx, features/mypage/components/MypageCard.test.tsx, features/mypage/components/MypageCard.tsx
> 
> - 리뷰 및 마이페이지에서 모임 클릭 시 상세 페이지로 이동하는 구조를 기존 '모임명 | 장소' 영역 클릭에서 전체 컴포넌트 클릭으로 변경했습니다.
> - 마이페이지 '모임명 | 장소' align center로 스타일 수정했습니다.
> - 마이페이지 모달 구조를 수정했습니다.
>
=> ♻️ 모든 리뷰, 마이페이지 모임 클릭 시 상세페이지로 이동하는 Link 구조 수정
