app/list/layout.tsx, app/list/page.tsx
리스트 페이지 퍼블리싱 하였습니다.
웹
모바일
웹 모바일 테블릿에 맞는 반응형으로 구현했습니다.
세션 설명을 위한 주석을 넣었읍니다 이후에 제거하도록하겠습니다.
이후에 정렬 섹션과
카드리스트 섹션을 추가 예정입니다.
>
> ex) 컴포넌트 분리에 대해서 조언주시면 감사하겠습니다..!
=> 🎨 리스트 페이지 퍼블리싱

components/common/Gnb.tsx
>
Gnb 공용 컴포넌트 작업했습니다.
기능 요구 사항 
>기존에는 페이지 이동만 가능했으나, 이번 작업에서는 로그인 여부에 따른 분기 처리가 추가되었고, 사용자 프로필 이미지를 클릭 시 드롭다운 메뉴가 활성화되어 마이페이지 이동과 로그아웃 기능을 제공하게 되었습니다.
> 지금은 일단 로그아웃 시 루트 ('/') 페이지로 이동하게 해놨습니다. 모임 찾기 페이지로 이동해야할 지, 어디로 이동하게 하는 게 좋을 지 의견주세요!
=>  ✨ Gnb 공통 컴포넌트 로그인 분기 처리 및 드롭다운 메뉴 추가

components/common/DropDown.tsx, components/common/DropDownItems.tsx
기존의 dropdown 컴포넌트에서 변경사항 알려드립니다!
-사용법 예시-
```
import React, { useState } from "react";
import DropDown from "@components/common/DropDown";
const ExampleItems = ["추가하고", "싶은", "아이템"];
function example() {
const [isOpen, setIsOpen] = useState(false);
const [selectedLocation, setSelectedLocation] = useState<string | null>(null);
const handleSelect = (selected: string) => {
setSelectedLocation(selected);
setIsOpen(false);
};
return (
<DropDown
items={locations}
onSelect={handleSelect}
isOpen={isOpen}
setIsOpen={setIsOpen}
selectedItem={selectedLocation}
variant="solid"
textSize="large"
/>
);
}
export default example;
```
DropDown 컴포넌트 위에 자유롭게 추가하셔서 드롭다운을 열고 닫을 컴포넌트 작성해주시면 됩니다!
사용해보시다가 문제되는 부분 있으면 말씀해주세요!
=> ✨ dropdown 버튼 제거 버전으로 수정

components/common/Input.tsx, features/auth/components/SigninForm.tsx, features/auth/components/SignupForm.tsx, types/form.d.ts
default는 text-base로 되어있습니다! auth페이지에서만 labelTextSize="sm"으로 사용하면 됩니다.
```
<InputForm
name="email"
id="email"
type="email"
label="아이디"
// 이 부분 추가
labelTextSize="sm"
//
placeholder="아이디를 입력하세요"
register={register}
rules={{ required: "아이디를 입력해주세요", pattern: emailPattern }}
errors={errors}
onBlur={() => trigger("email")}
/>
```
=> 🐛 label text size 옵션 추가

components/common/Popup.tsx, public/image/X.svg
모바일
태블릿/pc
컴포넌트 이름을 피그마에 있는 대로 Popup이라고 지었는데 생각해보니 해당 컴포넌트가 팝업의 역할과는 맞지 않는 것 같아 AlertModal으로 변경할 예정입니다..
=> 🎨 Popup 컴포넌트 스타일링

app/(layout_dafault)/list/page.tsx, components/common/DropDown.tsx, components/common/SortFilter.tsx, features/review/components/FilterBar.tsx
> ex) #이슈번호, #이슈번호
정렬필터 드롭다운 추가하였습니다.
리뷰 정렬
리스트 정렬
사용 예시
```jsx
// 정렬 옵션 변경 콜백 (SortFilter에서 호출)
const handleSortChange = (sortValue: string) => {
state 선언 필요
setSelectedSort(sortValue);
console.log("API 요청: 정렬 기준 =", sortValue);
};
리스트 페이지 경우
<SortFilter variant="list" onSortChange={handleSortChange} />
리뷰 페이지 경우
<SortFilter variant="list" onSortChange={handleSortChange} />
```
드롭다운 w 110 -> 120 수정되었습니다
=> ✨ 정렬필터 드롭다운 추가

components/common/Button.tsx
> 
> Button 컴포넌트 기존 w-full 때문에 size가 small인 경우에도 컨테이너 크기에 맞춰서 늘어나는 이슈가 있어 수정했습니다.
> > 제 페이지에선 해결된 것 같은데 혹시나 다른 페이지에서 문제가 있다면 알려주세요!
=> 🎨 Button 공통 컴포넌트 width 수정

apis/GatheringApi.tsx, apis/ReviewApi.ts, features/mypage/components/MypageCard.tsx, features/mypage/components/MypageCardList.tsx, features/mypage/components/WriteReviewModal.tsx, features/mypage/hooks/useCreateReview.ts, features/mypage/hooks/useDeleteGatheringJoinded.ts, features/mypage/hooks/useGetGatheringsJoined.ts, features/mypage/hooks/useGetMyReviews.ts
> #80 
> 마이페이지 작성한 리뷰 영역 데이터 조회 가능합니다.
> "예약 취소하기", "리뷰 작성하기" 버튼을 누르면 모달창이 띄워지고 원하는 기능이 수행됩니다.
PC View
Mobile View
> 모달창이 pc 화면에서 너무 작은가? 싶어요. 키우게 된다면 프로필 수정 모달도 같이 키워서 모달창 크기를 통일해야할지...? 아니면 모달의 레이아웃을 공통 컴포넌트로 빼고 그 안의 컨텐츠들은 prop으로 전달하게 해야할까요
> ~~아직 참여 시간이 지나지 않은 아이템이 상단에 보여집니다. << 이부분을 깜빡했네요...나중에 쿼리 수정해야할 것 같습니당 ㅎㅎㅎ...~~ => 쿼리 파라미터 수정했습니다.
=> ✨ 마이페이지 예약 취소 및 리뷰 작성 기능 추가

components/common/Gnb.tsx, hooks/useIsAuthenticated.ts, hooks/useIsMounted.ts, hooks/useLogout.ts, lib/axios.ts, types/error.ts
> #61 
> Gnb에 로그인한 사용자의 프로필 이미지를 표시합니다.
> 공통으로 쓰이는 로직은 커스텀훅으로 분리했습니다.
> 추가로 axios 인증 오류 처리 및 UnauthorizedError 클래스 추가했습니다. 호출한 곳에서 에러 핸들링할 때, 
>
```javascript
onError: (error: Error) => {
if (error instanceof UnauthorizedError) {
// alert 모달 또는 로그인 페이지로 리다이렉트 등 처리
} else {
// 에러 핸들링
}
```
> 이런 식으로 사용하시면 될 것 같습니다.
> NavMenu의 경우 usePathname으로 isActive를 체크해야 해서(없으면 새로고침 시 액티브 스타일이 사라짐) 클라이언트 컴포넌트여야하고, UserProfile도 커스텀훅 호출, 드롭다운 메뉴의 상태 관리가 필요해서 클라이언트 컴포넌트여야 하는데 둘다 Gnb에서만 쓰이는 컴포넌트라 따로 분리는 하지 않았습니다. 분리를 해서 Gnb는 서버 컴포넌트로 만드는 게 좋을까요...?
>
> 일단 인증 오류 에러처리를 해놓긴 했는데...이렇게 하는게 과연 맞는 지 모르겠어요...😭 뭔가 자꾸 이상한 느낌...ㅜㅜ 관련해서 아시는 분 있으시면 알려주세욥...🙏
=> ✨ Gnb 공통 컴포넌트 수정 및 axios 인증 오류 처리 추가

app/(layout_dafault)/liked/page.tsx, components/common/GatheringItem.tsx, features/list/hooks/useGetIdGatherings.ts, stores/favoriteStore.ts, types/gathering.d.ts
찜하기 페이지 제작 완료했습니다.
1. 찜하기를 위한 커스텀 훅 만들기
2. persist 스토어 만들기 (Zustand)
3. 버튼 누르면 찜하기에 담기도록 구현
4. 찜하기 상태 반영
5. 찜하기 목록 페이지 구현
6. placeholderData 깜박 거림 방지
남은사항
1. 찜한 모임 필터 추가
2. 하루지나면 장바구니 비우기
=> ✨ 찜하기 페이지 제작

components/common/GatheringItem.tsx, components/common/GatheringList.tsx, stores/hiddenGatheringStore.ts
유저가 마감된 챌린지를 숨길수 있는 기능을 만들었습니다.
마감된 모임에 손 버튼을 클릭하면 로컬스토리지에 id가 쌓이게 되고 필터링하여 보이지 않는 식으로 제작하였습니다.
추가사항으로 마감된 챌린지를 유저가 따로 보관하여 볼 수 있게할지 고민이네요.. 현재는 복구기능 없고 로컬스토리지를 비워야 가능합니다.
이미 마감된 모임이가 굳이 싶기도하고..
=> ✨ 마감된 모임 처리 기능 작성 

components/common/GatheringItem.tsx, features/list/GatheringStatusBadge.tsx, utils/dateFormatter.ts
게더링 아이템 3가지 내용 수정하였습니다.
1. 마감뱃지 현재 시간 대비 남은 날짜로 수정(남은일, 남은 시간, 곧마감됨,마감됨)
2. 칩인포 마감시간 ->  모임 만남 시간
3. 구름링 만나는 지역 온라인 수정
차후 구름링 지역 필터 수정 예정입니다
=> ✨ 게더링 아이템 수정(모임시간, 지역)

features/mypage/components/MyProfile.test.tsx, features/mypage/components/MypageCard.test.tsx, features/mypage/components/MypageCard.tsx
> 
> 마이페이지의 모임 목록에서 해당 모임의 상세 페이지로 이동하는 Link를 추가했습니다.
> MypageCard와 MyProfile 테스트코드 작성했습니다.
PC View
Mobile View
> 현재는 카드요소가 아닌 카드 내부의 "자세히 보기"를 눌러야 이동이 가능하게 해놨는데 카드 자체를 눌렀을 때 이동이 가능하게 해야할지 고민을 좀 해봐야할 것 같습니다.
=> ✨ 마이페이지에서 상세 페이지로 이동하는 링크 추가

components/common/ReviewItemWithImage.tsx, features/mypage/components/MypageCard.test.tsx, features/mypage/components/MypageCard.tsx, features/mypage/components/MypageCardList.tsx
>
> - 마이페이지, 리뷰페이지에서 상세페이지로 이동하는 링크 추가했습니다. 회의 결과대로 모임 이름 부분을 클릭하면 이동할 수 있게 수정 및 추가했습니다.
> - 마이페이지 나의 리뷰에서 모집 취소된 모임이 조회되던 오류 수정했습니다.
PC View
- 마이페이지
- 모든 리뷰
Mobile View
- 마이페이지
- 모든 리뷰
> 현재는 〉를 추가하여 클릭 유도를 진행하고 있습니다. 더 좋은 아이디어가 있으면 언제든지 알려주세요!
=> ✨ 마이페이지, 리뷰페이지에서 상세페이지로 이동하는 링크 추가

features/mypage/components/EditProfileModal.test.tsx, features/mypage/components/EditProfileModal.tsx, features/mypage/hooks/useEditProfile.ts, features/mypage/utils/fileUtils.test.ts, features/mypage/utils/fileUtils.ts
> 
> - EditProfileModal 컴포넌트의 뷰와 비즈니스 로직을 분리하여, 로직을 커스텀 훅(useEditProfile)으로 분리하였습니다.
> - 이미지 파일 크기 검증하는 함수를 별도의 유틸 함수로 분리하였습니다.
> - EditProfileModal 테스트코드 추가했습니다.
>
=> ♻️ EditProfileModal 컴포넌트 리팩토링

components/common/ReviewItemWithImage.tsx, constants/filter.ts, features/review/components/ClientReviewContainer.tsx, features/review/components/FilterBar.tsx, features/review/hooks/useReviewListViewModel.tsx, types/review.d.ts, utils/truncateText.ts
=> ♻️ 리뷰페이지 리팩토링

components/common/AlertModal.tsx
=> ♻️ 회원가입 완료 시 모달 닫기버튼 표시하지 않도록 UI개선

features/mypage/components/WriteReviewModal.tsx
> #80 
> - 리뷰작성 모달에 글자수 제한되게 하였습니다. (10자 이상 300자 이하)
> - 추가로 별점을 클릭 하지 않거나, 리뷰 코멘트를 작성하지 않은 경우 저장 버튼이 disable 상태가 되게 했습니다.
- 별점만 누른 경우, 리뷰 코멘트만 작성한 경우 (버튼 disable)
- 리뷰 코멘트 글자 수가 10자 이하, 300자 이상일 때 
- 올바른 입력
>
=> ✨ 리뷰작성 모달 글자수 제한 추가

components/common/ReviewItemWithImage.tsx, features/review/constants/review.ts
추가한 부분이 제가 보기에는 나쁘지 않은것 같습니다..!!
아이디어 주신 민주님 감사해요ㅎㅎ
=> ♻️ 모임일자를 기본 날짜로 표기 후 작성일 추가

features/list-detail/hooks/useClickHandlers.ts
> 
> 기존에 상세페이지에서 참여하기를 눌러도 마이페이지에서 바로 조회가 안되고 새로고침을 해야 보이는 이슈가 있었습니다. 
> - 상세페이지 참여하기 클릭 시 마이페이지에서 바로 조회가 가능하도록 쿼리 무효화하는 로직을 추가했습니다.
> @imsoohyeok 수혁님이 작성하신 훅 수정했는데 한번 확인해주시면 감사하겠습니다! 🙇‍♀️
=> 🐛 상세페이지 참여하기 클릭 시 관련 쿼리 무효화 추가

app/(layout_dafault)/list/page.tsx, features/list/components/ListContainer.tsx
모임리스트 코드 리팩토링 시 제거된 margin top 추가하였습니다.
=> ♻️ 리스트페이지 margin top 복구

features/mypage/components/MypageCard.test.tsx, features/mypage/components/MypageCard.tsx
> 
> - 마이페이지의 '예약 취소하기' 버튼 문구가 부자연스러운 것 같아 '참여 취소하기' 로 수정했습니다.
- 수정 전
- 수정 후
>
=> ♻️ 예약 취소하기 버튼 문구 수정

components/common/Chip.tsx, components/common/ChipFilterGroup.tsx, components/common/ExpiredFilterCheckbox.tsx, components/common/GatheringItem.tsx, components/common/GatheringList.tsx, constants/gathering.ts, features/list/components/GatheringStatusBadge.tsx, features/list/components/ListContainer.tsx, features/list/hooks/GatheringViewModel.ts, types/filters.ts, types/gathering.d.ts
모임리스트페이지 마감된 모임을 처리하는 체크박스 컴포넌트 제작 및 적용하였습니다.
기본상태
마감 포함 보기 선택 시 
1. 유저가 선택 시 마감된 모임을 볼 수 있도록 체크박스 컴포넌트제작하였습니다. (기본값 숨김)
2. 모임리스트 페이지에 마감체크박스 적용하였습니다.
3. 모임리스트 컴포넌트에 마감된 모임 필터링 시 hidden 기능 로직 추가하였습니다.
4. 이미지 비욜에 맞게 style 100으로 설정하였습니다.
=> ✨ 모임리스트페이지 마감된 모임 처리 체크박스 추가

components/common/ReviewItem.tsx, components/common/ReviewItemWithImage.tsx, components/common/ReviewListWithImage.tsx, types/review.d.ts
- 작성일 추가
- 이미지 최적화 적용 전
- 이미지 최적화 적용 후
=> ⚡️ 리뷰페이지 이미지 최적화

features/review/components/ClientReviewContainer.tsx
=> 🐛 필터바 위치 조정

components/common/DateFilter.tsx, features/list/components/FilterOptions.tsx, features/review/components/FilterBar.tsx
1. 모임리스트, 리뷰페이지 지역날짜 필터 위치 변경하였습니다.
2. 모바일 se 크기에 맞게 모바일버전 모달창 크기 추가
기존 구름링에 경우 온라인 모임으로 지역필터가 존재하지 않습니다.
모바일에서 모달창이 범위를 넘어가는 부분을 날짜필터를 앞으로 배치해도 괜찮다고 느꼈습니다.
적용후 모임리스트페이지
적용후 리뷰페이지
=> ♻️ 모임리스트, 리뷰페이지 지역,날짜 필터 위치 변경

features/list-detail/components/FloatingBar.tsx, features/list-detail/components/ListDetailContent.tsx, features/list-detail/components/ReviewSection.tsx
=> ♻️ 상세페이지 수정사항 반영

app/page.tsx, features/auth/components/AuthPageContainer.tsx
- fade-in 제거 전
- fade-in 제거 후
새롭게 알게 된 사실인데 LCP 후보에 fade-in 애니메이션이 적용되는게 성능에 치명적이라고 합니다... 
- 관련 자료
https://ui.toast.com/posts/ko_20220426#fade-in-%ED%95%98%EC%A7%80-%EC%95%8A%EA%B8%B0
=> ⚡️ 랜딩페이지 성능 개선

features/list/hooks/GatheringViewModel.ts, hooks/useQueryString.ts, hooks/useQueryTabIndex.ts
새로고침 시 뒤로가기 시 필터가 잘 유지되나 tabindex를 통해서 내용을 수정하는 경우 필터가 바로 적용되지 않는 문제 발생
문제 원인
초기값은 유즈파람스로 잘 변경되었으나 이후에 값들 state로 관리되기 때문에 수정로직 필요
해결 방법
next의 useSearchParams는 상태관리 까지 자동업데이트 되는 기능이 있어 useSearchParams 관리하는 코드로 수정
=> ♻️  유즈파람스 useState ->useSearchParams 관리 코드 변경

app/layout.tsx
> 
> - Gnb와 마이페이지 헤딩이 겹치는 이슈가 있어서 Gnb 영역의 z 인덱스 수정했습니다.
- 수정 전
- 수정 후
>
=> 🎨 Gnb 영역 z 인덱스 수정
